//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarMisinYokMusun {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Ayar : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ayar defaultInstance = ((Ayar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ayar())));
        
        public static Ayar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int dusukTeklif {
            get {
                return ((int)(this["dusukTeklif"]));
            }
            set {
                this["dusukTeklif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool devamEtseydin {
            get {
                return ((bool)(this["devamEtseydin"]));
            }
            set {
                this["devamEtseydin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hile {
            get {
                return ((bool)(this["hile"]));
            }
            set {
                this["hile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kodevreni")]
        public string hilesifre {
            get {
                return ((string)(this["hilesifre"]));
            }
            set {
                this["hilesifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bilgi {
            get {
                return ((bool)(this["bilgi"]));
            }
            set {
                this["bilgi"] = value;
            }
        }
    }
}
